[package]
name = "loom-record"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anstream.workspace = true
loom-core = { path = "../loom-core" }
loom-process.workspace = true
loom-runner = { path = "../loom-runner" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.151"

[dev-dependencies]
loom-test-support = { workspace = true }

[lints]
workspace = true
