[package]
name = "loom-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "loom"
path = "src/main.rs"


[dependencies]
anstream.workspace = true
anstyle.workspace = true
clap.workspace = true
indicatif.workspace = true
loom-core = { path = "../loom-core" }
loom-manifest = { path = "../loom-manifest" }
loom-runner = { path = "../loom-runner" }
loom-sandbox = { path = "../loom-sandbox" }
loom-process.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.151"

[dev-dependencies]
loom-test-support = { workspace = true }

[lints]
workspace = true
