[package]
name = "loom-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "loom"
path = "src/main.rs"


[dependencies]
anstream.workspace = true
anstyle.workspace = true
clap.workspace = true
indicatif.workspace = true
loom-core = { path = "../loom-core" }
loom-daemon = { path = "../loom-daemon" }
loom-manifest = { path = "../loom-manifest" }
loom-record = { path = "../loom-record" }
loom-runner = { path = "../loom-runner" }
loom-sandbox = { path = "../loom-sandbox" }
loom-process.workspace = true

[dev-dependencies]
loom-schedule = { path = "../loom-schedule" }
loom-test-support = { workspace = true }

[lints]
workspace = true
